### ISSUE TITLE
grep's -P is required

### ISSUE THREAD

**Issue by afoster** [chasinglogic/release.sh#1]
Hi, thanks for the great script!

I found you're relying on grep's `-P` switch, which isn't supported by the grep that ships with macOS. I'm not sure if there's an easy way to test for that. In my case I was able to `brew install grep` which installs GNU grep as `ggrep`, but this won't work for everyone.

Cheers

**Comment by chasinglogic** [comment]
Good catch, I can certainly check for the presence of gnu grep, I actually have grep aliased to GNU grep on my mac so I never realized!

I'll be working on a fix this week. Thanks for the report

**Comment by afoster** [comment]
Cheers. The other switch-related issue I came across was `curl`'s `-T` in place of `--data-binary` for Github artifact uploads. But that appears consistent across my macOS and Linux boxes.

**Comment by chasinglogic** [comment]
I believe I've fixed the grep issue, can you expand on the curl problem? I don't have a problem on my Fedora 25 or OSX box and as far as I can tell I'm using system curl on OSX

**Comment by afoster** [comment]
I found that using --data-binary was causing curl to upload the filenames as the content of the artifacts instead of the actual content of the files, thus resulting broken uploads. On my system I had to swap out `--data-binary` with `-T` for it to work as expected.

For curl 7.51.0 (x86_64-apple-darwin16.0)

Output of `curl --help`:

`      --data-binary DATA  HTTP POST binary data (H)`
` -T, --upload-file FILE  Transfer FILE to destination`

The switches appear the same on an older Ubuntu box:

curl 7.35.0 (x86_64-pc-linux-gnu)

`--data-binary DATA  HTTP POST binary data (H)`
` -T, --upload-file FILE  Transfer FILE to destination`

**Comment by chasinglogic** [comment]
Cool beans I updated it thanks for your help!
